server:
  port: 8011

spring:
  datasource:
    url: jdbc:h2:file:~/spiderdb
    driver-class-name: org.h2.Driver
    username: root
    password: spider
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true



logging:
  config: classpath:logback-spring.xml
